import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';

import { inter } from '@/ui/fonts';
import { cn } from '@/utils/cn';
import '@/styles/globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" className={cn(inter.variable)} suppressHydrationWarning>
			<body className="min-h-screen bg-background font-inter antialiased">{children}</body>
		</html>
	);
}
